### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mgrachev** [philipgiuliani/coverage#20]
[Enter steps to reproduce below:]
1. Open coverage status view
2. Сlicked on the title of the first column to sort

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [coverage](https://github.com/philipgiuliani/coverage) package, v0.6.1
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/mgrachev/.atom/packages/coverage/node_modules/tablesort/src/tablesort.js:87

TypeError: Cannot read property '0' of undefined
  at Object.Tablesort.sortTable (/Users/mgrachev/.atom/packages/coverage/node_modules/tablesort/src/tablesort.js:87:63)
  at HTMLTableCellElement.onClick (/Users/mgrachev/.atom/packages/coverage/node_modules/tablesort/src/tablesort.js:42:22)

```
### Commands

```
     -2:34 editor:newline (atom-text-editor.editor.is-focused)
     -2:33.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:33.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:30.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:30.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:30.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:30.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:30.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:30.3.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -2:30 core:move-up (atom-text-editor.editor.is-focused)
     -2:29.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:29.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:29.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:29.4.0 editor:indent (atom-text-editor.editor.is-focused)
  4x -2:29 core:move-down (atom-text-editor.editor.is-focused)
     -2:26.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-clojure",
      "language-csharp",
      "language-java",
      "language-perl",
      "language-php",
      "language-python",
      "language-toml",
      "term3",
      "term2",
      "minimap-autohide",
      "flex-tool-bar",
      "symbols-view",
      "language-gitignore",
      "language-rspec",
      "language-rspec-plus",
      "rspec"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.4.0
coverage, v0.6.1
file-icons, v1.6.11
git-control, v0.4.0
highlight-selected, v0.10.1
language-arduino, v0.3.1
language-generic-config, v0.2.0
language-slim, v0.5.0
linter, v1.10.0
linter-erb, v0.1.1
linter-rubocop, v0.4.4
linter-ruby, v1.2.0
linter-slim, v1.0.0
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
pretty-json, v0.4.1
project-manager, v2.6.5
tool-bar, v0.1.9
tool-bar-almighty, v0.2.2

# Dev
No dev packages
```

**Comment by partydrone** [comment]
:+1:
