### ISSUE TITLE
Failed to activate the coverage package

### ISSUE THREAD

**Issue by joaomnb** [philipgiuliani/coverage#21]

**Comment by aequitas** [comment]
[Enter steps to reproduce below:]
1. install package

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [coverage](https://github.com/philipgiuliani/coverage) package, v0.6.1

### Stack Trace

Failed to activate the coverage package

```
At atom.views.getView(...).querySelector(...).appendLeft is not a function

TypeError: atom.views.getView(...).querySelector(...).appendLeft is not a function
    at Object.module.exports.initializeStatusBarView (/Users/johanbloemberg/.atom/packages/coverage/lib/coverage.coffee:57:68)
    at Object.module.exports.activate (/Users/johanbloemberg/.atom/packages/coverage/lib/coverage.coffee:42:8)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:333:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:624:20
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:809:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:601:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:379:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:162:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:31.7.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused)
  3x -0:10.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-csharp",
      "language-java",
      "language-objective-c",
      "language-ruby-on-rails",
      "markdown-deluxe",
      "coverage-python",
      "coverage-gutter",
      "coverage-python"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".codekit-cache",
      "bower_components",
      "node_modules",
      "tmp",
      "dist",
      "*.pyc",
      "__pycache__",
      "*results.xml",
      "*.egg-info",
      ".cache",
      ".tox"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "markdown-preview"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "coverage": {}
}
```

### Installed Packages

``` coffee
# User
MagicPython, v0.5.7
aligner, v0.17.4
aligner-puppet, v0.1.1
atom-alignment, v0.12.1
atom-fix-path, v0.1.0
atom-jinja2, v0.5.0
atom-ternjs, v0.12.2
color-picker, v2.0.14
column-select, v0.2.0
coverage, v0.6.1
file-icons, v1.6.13
language-arduino, v0.4.1
language-ember-htmlbars, v0.3.0
language-groovy, v0.5.0
language-ninja, v1.0.0
language-puppet, v0.15.0
language-terraform, v0.6.0
linter, v1.11.3
linter-jshint, v1.2.2
linter-puppet-lint, v0.6.2
linter-pylama, v0.2.5
minimap, v4.19.0
python-isort, v0.0.7
selection-highlight, v0.1.4

# Dev
No dev packages
```

**Comment by juanignaciosl** [comment]
Same happened to me today just installing coverage from Atom.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.4
**Thrown From**: [coverage](https://github.com/philipgiuliani/coverage) package, v0.6.1

### Stack Trace

Failed to activate the coverage package

```
At atom.views.getView(...).querySelector(...).appendLeft is not a function

TypeError: atom.views.getView(...).querySelector(...).appendLeft is not a function
    at Object.module.exports.initializeStatusBarView (/Users/juanignaciosl/.atom/packages/coverage/lib/coverage.coffee:57:68)
    at Object.module.exports.activate (/Users/juanignaciosl/.atom/packages/coverage/lib/coverage.coffee:42:8)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -3:10.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:05.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:05.1.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -2:54.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:31.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.3.0 pane:show-previous-item (atom-text-editor.editor.mini.is-focused)
     -0:28.8.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:27.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "._*",
      "coverage",
      ".grunt",
      ".idea",
      ".sass-cache",
      "log",
      "tmp",
      ".byebug_history",
      ".vim-session-*"
    ]
  },
  "coverage": {}
}
```

### Installed Packages

``` coffee
# User
coverage, v0.6.1
eclipse-keybindings, v0.9.0
linter, v1.11.3
linter-rubocop, v0.4.7
linter-ruby, v1.2.2

# Dev
No dev packages
```

**Comment by kenden** [comment]
I got this error on version 0.6.1 with atom 1.8.0
Why was the bug closed?

**Comment by BitOfUniverse** [comment]
Have the same issue, going to prepare PR for this bug.

**Comment by scippio** [comment]
bump? pls reopen it... The bug is still here.

**Comment by elliotb** [comment]
This is occurring for me on a fresh install.

**Comment by prevostcorentin** [comment]
Occurring on Ubuntu 16.04 LTS

**Comment by mkg20001** [comment]
Still occurring in atom 1.8

**Comment by ryanfelton** [comment]
Please reopen.  Still Occurring. 

Mac OS: 10.13.2
Atom: 1.22.1

```
atom.views.getView(...).querySelector(...).appendLeft is not a function
Hide Stack Trace
TypeError: atom.views.getView(...).querySelector(...).appendLeft is not a function
    at Object.initializeStatusBarView (/Users/username/.atom/packages/coverage/lib/coverage.coffee:57:68)
    at Object.activate (/Users/username/.atom/packages/coverage/lib/coverage.coffee:42:8)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)


```

**Comment by aarighi** [comment]
Still occurring, even now. @joaomnb why did you close?

[Enter steps to reproduce:]

1. install `coverage` package from Atom Settings/Install page

**Atom**: 1.25.0 ia32
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [coverage](https://github.com/philipgiuliani/coverage) package 0.6.1


### Stack Trace

Failed to activate the coverage package

```
At atom.views.getView(...).querySelector(...).appendLeft is not a function

TypeError: atom.views.getView(...).querySelector(...).appendLeft is not a function
    at Object.initializeStatusBarView (/packages/coverage/lib/coverage.coffee:57:68)
    at Object.activate (/packages/coverage/lib/coverage.coffee:42:8)
    at Package.activateNow (~/AppData/Local/atom/app-1.25.0/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.25.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.25.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.25.0/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.25.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.25.0/resources/app/src/package-manager.js:695:42)
    at ~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.25.0/resources/app/src/buffered-process.js:267:15)
    at bufferStream (~/AppData/Local/atom/app-1.25.0/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (~/AppData/Local/atom/app-1.25.0/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
     -9:21.3.0 core:paste (input.hidden-input)
     -9:18.4.0 core:backspace (input.hidden-input)
     -9:15.7.0 core:move-right (input.hidden-input)
     -9:15.6.0 markdown-writer:indent-list-line (input.hidden-input)
  2x -9:15 core:move-down (input.hidden-input)
  2x -9:14.5.0 core:move-left (input.hidden-input)
     -9:14.1.0 markdown-writer:indent-list-line (input.hidden-input)
  2x -9:13.5.0 core:move-down (input.hidden-input)
  2x -9:13.1.0 core:move-left (input.hidden-input)
     -9:12.7.0 markdown-writer:indent-list-line (input.hidden-input)
     -9:03.0 core:backspace (input.hidden-input)
  2x -9:02.2.0 core:move-right (input.hidden-input)
     -8:52.2.0 core:paste (input.hidden-input)
     -8:50.4.0 core:undo (input.hidden-input)
     -4:22.2.0 core:confirm (input.hidden-input)
  2x -2:37.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-clock 0.1.16 
atom-html-preview 0.2.5 
atom-ide-ui 0.9.1 
atom-json-editor 0.4.1 
atom-overtype-mode 0.4.0 
autoclose-html 0.23.0 
autocomplete-python 1.10.5 
autohide-tree-view 0.25.1 
coverage 0.6.1 
doxygen-snippets 0.1.1 
file-type-icons 1.3.4 
Hydrogen undefined 
ide-html 0.4.1 
language-batchfile 0.7.1 
language-bison-flex 0.3.1 
language-dot 1.7.0 
language-latex 1.1.1 
language-sml 0.7.0 
markdown-pdf 2.1.0 
markdown-writer 2.7.3 
open-in-browser 0.5.2 
platformio-ide-terminal 2.8.0 
selection-highlight 0.1.6 
wakatime 7.0.4 
```

**Comment by joaomnb** [comment]
I apologize!! This was a long time ago and I moved to a different editor... I wasn't being notified about this, just realized now. I reopened it, sorry again!

**Comment by allisonphillips** [comment]
@philipgiuliani I have this problem as well and it looks like it hasn't been updated in a long time. Do you still plan on supporting this package? There's a comment on another issue saying to stay tuned.

**Comment by miguelms95** [comment]
The same error still happens.

[Enter steps to reproduce:]

1. install coverage package from Atom Settings > Install page.


**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: [coverage](https://github.com/philipgiuliani/coverage) package 0.6.1


### Stack Trace

Failed to activate the coverage package

```
At atom.views.getView(...).querySelector(...).appendLeft is not a function

TypeError: atom.views.getView(...).querySelector(...).appendLeft is not a function
    at Object.initializeStatusBarView (/packages/coverage/lib/coverage.coffee:57:68)
    at Object.activate (/packages/coverage/lib/coverage.coffee:42:8)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3293263)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3292675)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3290285)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3292535)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3292478)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382285)
    at /usr/share/atom/resources/app/static/<embedded>:11:937303
    at r (/usr/share/atom/resources/app/static/<embedded>:11:931909)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1128972)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1129126)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1127728)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

### Commands

```
     -3:22.6.0 application:reopen-project (div.tool-panel.tree-view)
     -2:56 core:paste (input.hidden-input)
     -2:50.7.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:53.5.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -1:50.9.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:49.6.0 core:confirm (input.hidden-input)
     -1:45.9.0 symbols-tree-view:toggle (input.hidden-input)
  5x -1:40.1.0 core:move-down (input.hidden-input)
     -1:36.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:34.8.0 editor:newline (input.hidden-input)
     -1:34.5.0 core:paste (input.hidden-input)
     -1:31.2.0 core:move-up (input.hidden-input)
     -1:31.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
  5x -1:31.2.0 editor:select-to-beginning-of-word (input.hidden-input)
  3x -1:28.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.3.0 
coverage 0.6.1 
git-time-machine 2.1.0 
goto-definition 1.3.4 
language-haml 0.32.1 
ruby-block 0.3.6 
split-diff 1.6.1 
symbols-tree-view 0.14.0 
tree-view-filter 0.5.5 
tree-view-git-status 1.5.2 
```
