### ISSUE TITLE
Uncaught TypeError: Cannot read property '4' of undefined

### ISSUE THREAD

**Issue by knightq** [philipgiuliani/coverage#22]
[Enter steps to reproduce below:]
1. Open coverage status view
2. Сlicked on the title of the percentage column to sort

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [coverage](https://github.com/philipgiuliani/coverage) package, v0.6.1
### Stack Trace

Uncaught TypeError: Cannot read property '4' of undefined

```
At /Users/andreasalicetti/.atom/packages/coverage/node_modules/tablesort/src/tablesort.js:87

TypeError: Cannot read property '4' of undefined
    at Object.Tablesort.sortTable (/Users/andreasalicetti/.atom/packages/coverage/node_modules/tablesort/src/tablesort.js:87:63)
    at Object.Tablesort.refresh (/Users/andreasalicetti/.atom/packages/coverage/node_modules/tablesort/src/tablesort.js:227:22)
    at coverage-panel-view.PanelView.update (/Users/andreasalicetti/.atom/packages/coverage/lib/panel-view.coffee:58:16)
    at Object.module.exports.updatePanelView (/Users/andreasalicetti/.atom/packages/coverage/lib/coverage.coffee:74:16)
    at /Users/andreasalicetti/.atom/packages/coverage/lib/coverage.coffee:68:10
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
     -6:24.6.0 core:copy (atom-text-editor.editor.is-focused)
  2x -6:24.4.0 core:paste (atom-text-editor.editor.is-focused)
     -6:23.5.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -6:23.2.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -6:22 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -6:18.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.5.0 coverage:toggle (atom-text-editor.editor)
     -0:07.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 coverage:toggle (atom-text-editor.editor)
     -0:04.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 coverage:refresh (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-less",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-toml"
    ],
    "ignoredNames": [
      ".csv",
      ".log"
    ]
  },
  "coverage": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
atom-beautify, v0.29.2
change-case, v0.6.0
coverage, v0.6.1
javascript-snippets, v1.2.1
language-haml, v0.24.0
linter, v1.11.4
linter-rubocop, v0.4.7
ruby-test-switcher, v1.2.1
tasks, v2.6.0

# Dev
No dev packages
```

**Comment by knightq** [comment]
Same as #20
